title: Cássio Batista Pereira # name of the site
author: Cássio Pereira # name of site's author
email: cassio@cassiobp.com.br # email of site's author
url: cassiodeveloper.com.br # root address of the site
baseurl: "" # subpath of the site, e.g. "/blog" (leave it blank "" if you're site shouldn't use a subpath)
description: > # description of the site (multiple lines allowed)
  Cássio Batista Pereira, a.k.a. @cassiodeveloper, é Desenvolvedor e Arquiteto de Software por formação. Ele atua como Cyber Security Engineer e assim auxilia as empresas e profissionais a construírem soluções mais seguras. Possui duas décadas de experiência no mercado de T.I. e Segurança da Informação nos mais variados segmentos de negócios, onde obteve conhecimento para trabalhar com diferentes tecnologias, linguagens de programação e processos. É evangelista da cultura de Desenvolvimento Seguro.

permalink: /:slug.html

favicon: "logo.png" # name+extension of favicon (which must be put on the root folder)
# goat_counter: "yoursitename" # put your GoatCounter name if you want to use GoatCounter analytics

remote_theme: riggraz/no-style-please # if you are using GitHub Pages, change it to remote_theme: riggraz/no-style-please

theme_config:
  appearance: "auto" # can be "light", "dark" or "auto"
  back_home_text: ".." # customize text for homepage link in post layout
  date_format: "%Y-%m-%d" # customize how date is formatted
  show_description: true # show blog description in home page

sass:
  style: :compressed

plugins:
  - jekyll-feed
  - jekyll-seo-tag
