title: Cássio Batista Pereira # name of the site
author: Cássio Pereira # name of site's author
email: cassio@cassiobp.com.br # email of site's author
url: cassiodeveloper.com.br # root address of the site
baseurl: "" # subpath of the site, e.g. "/blog" (leave it blank "" if you're site shouldn't use a subpath)
description: > # description of the site (multiple lines allowed)
  Cassio Batista Pereira, a.k.a. @cassiodeveloper, is a Software Developer and Architect by formation. He acts as a Cyber Security Engineer and thus helps companies and professionals to build safer solutions. He has two decades of experience in the IT market and Information Security in the most varied business segments, where he gained knowledge to work with different technologies, programming languages and processes. He is an evangelist for the Secure Development culture.

permalink: /:slug.html

favicon: "logo.png" # name+extension of favicon (which must be put on the root folder)
# goat_counter: "yoursitename" # put your GoatCounter name if you want to use GoatCounter analytics

remote_theme: riggraz/no-style-please # if you are using GitHub Pages, change it to remote_theme: riggraz/no-style-please

theme_config:
  appearance: "auto" # can be "light", "dark" or "auto"
  back_home_text: ".." # customize text for homepage link in post layout
  date_format: "%Y-%m-%d" # customize how date is formatted
  show_description: true # show blog description in home page

sass:
  style: :compressed

plugins:
  - jekyll-feed
  - jekyll-seo-tag
